### ISSUE TITLE
Should we deprecate .bufferWhileBy?

### ISSUE THREAD

**Issue by pozadi** [pozadi/kefir#105]
`.bufferBy` can be used instead:

```js
foo.bufferWhileBy(bar);

foo.bufferBy(bar.filter((x) => !x));
```

The additional `.filter` at the end usually won't be _additional_, because usually a `.map()` is used to create `bar` (stream of booleans), and it will be simply replaced by a `.filter()`.

**Comment by kryptt** [comment]
my two cents: Yes, I would, especially if one of kefir's goals is a minimal API....

**Comment by pozadi** [comment]
Whoa, using this same reasoning we can also deprecate `.skipWhileBy` and `.takeWhileBy` :smiley: 

```js
foo.skipWhileBy(bar);
foo.skipUntilBy(bar.filter((x) => !x);

foo.takeWhileBy(bar);
foo.takeUntilBy(bar.filter((x) => !x);
```

**Comment by pozadi** [comment]
@kryptt thanks! Every simple "+1" on issues like that help me make sure I don't do anything stupid :)

**Comment by pozadi** [comment]
Actually `.bufferWhileBy` has two notable differences from `.bufferBy`:
 
 - It flushes the buffer at an event from _main source_, while `.bufferBy` flushes on an event from _controller source_.
 - In `.bufferBy` you can only flush the buffer on arbitrary time, while in `.bufferWhileBy` you can turn on and off the buffering.

Looks this two are not replaceable by each other. Good news these differences don't apply to `.skip* / .take*` pairs, so we still can deprecate those.
