### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by DNizovtsev** [pozadi/kefir#15]
For first thanks for nice library. I want to use it instead of bacon in my project. But library does not support errors handling right now. 
If you do not mind I can add errors handling like bacon: Error object, onError, errors, skipErrors, retry methods for Observables.

Any thoughts?

**Comment by pozadi** [comment]
I finished base error support in a branch https://github.com/pozadi/kefir/pull/28 (see a little more detailed description of what been done in PR comment).
Next step is to add helper methods here and there, like `.mapErrors` etc.

**Comment by pozadi** [comment]
v0.5.0 released with errors support. See changelog https://github.com/pozadi/kefir/blob/master/changelog.md#050

**Comment by pozadi** [comment]
See also https://pozadi.github.io/kefir/#about-errors

**Comment by chicoxyzzy** [comment]
:+1:

**Comment by gnapse** [comment]
One of the features mentioned in this issue's original text is the retry capability, as provided in Bacon and RxJS. Is this covered in these recent additions? Because at first sight it would appear it's not. And if that's the case, are there any plans on adding support to it? or perhaps an easy way to achieve it by composing current methods?

**Comment by pozadi** [comment]
You can do retry using [repeat](http://pozadi.github.io/kefir/#repeat) method. Something like this:

```js
var ajaxResult = Kefir.repeat(function() {
  If (i < 2) {
    // on first two tries ignore errors
    return ajaxCall().skipErrors(); 
  } if (i === 2) {
    // on the third try let the error (if there will be a error) show up in `ajaxResult`
    return ajaxCall(); 
  } else {
    // on the fourth iteration just return `false` to stop the cycle
    return false; 
  }
}).take(1); 
// without `.take` it will make three ajax calls even if all of them was success
```

Maybe we need a convenient `.retry` method that will basically do the logic above. But for now you can use `.repeat`.

**Comment by gnapse** [comment]
Thanks, that'll do the trick, but +1 for that convenience method `.retry`. It'll definitely be a good addition. 

Thanks for the library by the way. Its paradigm is much better than that of RxJS (errors do not end streams, and the avoidance of synchronous observables). Plus it's way faster than Bacon.js. That makes up for the lack of some convenience methods like this one.

**Comment by maple-leaf** [comment]
The `repeat` trick is not as clear as a `retry` method, votes for adding a `retry` method.
And thanks for the great job.

**Comment by rpominov** [comment]
If I understand correctly how `retry` works, it won't work with "hot" observables (observables that have many subscribers connected to single original source of events). And in Kefir we have only "hot" observables.

**Comment by maple-leaf** [comment]
I think `bacon.js` is also `hot only`, take a look at its api ref, https://baconjs.github.io/api.html, scroll to the end, and you will see this description at the `For RxJs Users` section: `Also, there are no "cold observables", which means also that all EventStreams and `. So, I think maybe `retry` can work with `hot`.

**Comment by rpominov** [comment]
I mean if we do retry in Kefir, it will be not like in Rx `obs.retry()` but rather:

```js
Kefir.retry(() => { 
  // This function must return `obs` that's guaranteed 
  // to not have any subscribers at the moment.
  // Ideally just create fresh observable from a scratch.
  return obs
})
```

In example above `ajaxCall` is such a function.

**Comment by rpominov** [comment]
Yeah. Notice that in `Bacon` API looks like this `Bacon.retry({source: ajaxCall})`. Given the restrictions on what `ajaxCall` must return, I think it will be confusing and bug prone for people to use such `retry`.
