### ISSUE TITLE
how to remove listeners?

### ISSUE THREAD

**Issue by sunwukung** [pozadi/kefir#32]
I've just started taking kefir for a spin, and I have a question about ending streams derived from DOM events. there appear to be a couple of methods of attaching event handlers (no $ for me) - K.fromBinder and K.fromEvent. How do I detach the event listener when using K.fromEvent? I've inspected the proto chain, and I've tried firing various "off" methods - but the stream still emits the events from the element:

https://gist.github.com/sunwukung/69c1be92215112e93a87

**Comment by sunwukung** [comment]
I figured out my problem and updated the gist

1. I was using the wrong off method
2. I was not passing in the handler to unsub

**Comment by pozadi** [comment]
Yeah, you figured it right. 

But also in most cases you don't need to use `.off*` methods, instead you can define a condition when stream ends, and then everything detaches automatically. For example `mousemoveStream.take(100).onValue(fn)` — here the _condition_ will be "end after 100 values". There is also `.takeWhile` and `.takeWhileBy` methods that can be used to define end condition.
