### ISSUE TITLE
Should .take() unsubscribe from the source when it's done?

### ISSUE THREAD

**Issue by myndzi** [pozadi/kefir#35]
Test code:

    'use strict';

    var Kefir = require('kefir');

    var thing = Kefir.fromBinder(function (emitter) {
        console.log("subscribed");
        emitter.emit(1);
        
        var timer = setTimeout(function () {
            emitter.emit(2);
        }, 1000);
        
        return function () {
            console.log("unsubscribed");
            clearTimeout(timer);
        };
    });

    thing.take(1).onValue(function (val) {
        console.log(val);
    });

The unsubscribe callback is never called

According to [this](https://github.com/pozadi/kefir/issues/32) issue, the subscriber to 'thing' should detach automatically after 1 item, so maybe this is a bug with fromBinder?

Interestingly, if I change it to take(2), the callback *is* called

**Comment by myndzi** [comment]
It appears to be the fault of the synchronous 'emit' -- if I make that asynchronous by wrapping it in  process.nextTick(), it behaves as expected.

**Comment by pozadi** [comment]
Yes, there is a bug. Not easy to fix on the first look though. Funny that I found similar bug in Bacon recently https://github.com/baconjs/bacon.js/issues/523

The bug occurs when you truing to unsubscribe from a stream in response of first value from it, and that first value is emitted synchronously.

Will think of how to fix this.

**Comment by pozadi** [comment]
The fix was actually pretty easy. Fixed in v0.5.2.

**Comment by myndzi** [comment]
Cool, thanks!

Back to trying to get pagination to work
