### ISSUE TITLE
No way to introduce an error into a stream

### ISSUE THREAD

**Issue by rooftopsparrow** [pozadi/kefir#38]
I've tried many things but I can't seem to be able to introduce an error into a stream.

For example, if I get a weird value in a stream that I want to handle up the stream, I'd like to create an error and continue. There seems to be no obvious way to do this without `flatMap`ing a error stream.

Some things I tried:

```js
Kefir.constant('hello').
map(function(x) { throw new Error(x); }).
onError(function(e) { console.error('GOT ERROR', e) });
// Above doesn't work, works just like a throw anywhere else

Kefir.constant('hello').
map(function(x) { return new Error(x); }).
onError(function(e) { console.error('GOT ERROR', e) });
// Does not work, get an Error object in _current 

Kefir.constant('hello').
flatMap(function(x) { return Kefir.constantError(new Error(x)); }).
onError(function(e) { console.error('GOT ERROR', e) }).
onValue(function(v) { console.log('got value', v); });
// Works in general
```

Would love a method or some way to trigger this without having to flatMap a stream. Any advice?

Also, in the above `flatMap` scenario, if I don't attach a `onValue` handler, I still don't get the error. I'm assuming that because of the lazy nature of Kefir the `_active` property only is true when there is a `onValue` handler?

Thanks!

**Comment by pozadi** [comment]
Hi, there is number of methods that can help you to do this. You already mentioned `flatMap`, and there is also [errorsToValues](http://pozadi.github.io/kefir/#errors-to-values) and [withHandler](http://pozadi.github.io/kefir/#with-handler).

About `flatMap` example not working without `onValue` handler, I can't reproduce that. This works fine:
```js
Kefir.constant('hello').
flatMap(function(x) { return Kefir.constantError(new Error(x)); }).
onError(function(e) { console.error('GOT ERROR', e) });
// > GOT ERROR Error: hello {stack: (...), message: "hello"}
```

**Comment by pozadi** [comment]
And to answer the question "the _active property only is true when there is a onValue handler?": No, all handlers (`onValue`, `onError`, `onEnd`, `onAny`) activate the observable.

**Comment by rooftopsparrow** [comment]
The `flatMap.onError` does work for me. For some reason when I was testing it, but I fear I probably messed something up while figuring this out (most likely a copy-paste mess up :disappointed: ).

Thanks for the great effort and contribution to the community! :+1:

**Comment by pozadi** [comment]
Sorry, just noticed, I wrote `errorsToValues`, but it should be `valuesToErrors` of course. But I guess you've figured that out already :)
