### ISSUE TITLE
Version 1.0.0 release

### ISSUE THREAD

**Issue by pozadi** [pozadi/kefir#40]
I am going to release 1.0.0 in near future. There won't be much changes from current latest version, I just think the API is stable enough to start using real [SemVer](http://semver.org/).

The current list of changes for 1.0.0 is:

 - [x] move jQuery plugin to a separate repo
 - [x] remove deprecated [.withDefault](http://pozadi.github.io/kefir/#with-default) method

If you think there is something else that should be done, please comment on this issue.

**Comment by gching** [comment]
Is it reasonable to add some more jQuery wrapper functions for 1.0.0 so that it can be more than just a separate repo with two specific addons? Maybe ajax or some other helpers :+1:

**Comment by pozadi** [comment]
Yes, I agree that jQuery wrapper probably needs more functionality. For now I just moved what we already have to a separate repository https://github.com/pozadi/kefir-jquery . And `kefir-jquery` starts from v1.0.0 to follow semver from the begining.

But I opened this issue to discuss what we might need to do in main kefir repository before 1.0.0 release.

**Comment by pozadi** [comment]
Ok, done!
