### ISSUE TITLE
Switch operator?

### ISSUE THREAD

**Issue by staltz** [pozadi/kefir#41]
Is there in Kefir an equivalente to [Rx's switch](http://reactivex.io/documentation/operators/switch.html)? I couldn't find from the docs. The closest one was flatten, but seems to be for arrays only.

**Comment by pozadi** [comment]
Yep, [.flatMapLatest](https://pozadi.github.io/kefir/#flat-map-latest), same as in Bacon.

**Comment by staltz** [comment]
Called with no arguments, right? Sweet.
I'm quite positively surprised with Kefir. Faster than others, smaller than others, and the API is elegant. I need to give it a try, and leave library popularity aside.

**Comment by pozadi** [comment]
Yes, if called with no arguments it works like `.switch`.

Very nice to hear that. API is mostly borrowed from Bacon, but I'm trying to make it more consistent and adding my own ideas here and there.
