### ISSUE TITLE
a way to get the current value of a property

### ISSUE THREAD

**Issue by mhelvens** [pozadi/kefir#50]
Kefir.js, like Bacon.js, doesn't offer an easy way to get the *current value* from a property:

    property.currentValue()

This is for reasons of purism, I believe. I.e., we're not *supposed to want* to get the current value that way. Is that correct? If so, could you explain the benefits of this philosophy?

In any case, I would like to request this as a feature. There is already a way to twist the public interface to do it anyway:

    var current;
    var fn = function (v) { current = v };
    property.onValue(fn);
    property.offValue(fn);

Why not provide a method or (read-only) property to do this the easy way?

**Comment by pozadi** [comment]
Yes one reason is that users not *supposed* to want this, but have to admit I have no clear explanation why this is bad, only some intuition feeling. Maybe @raimohanska could tell more about this.

But there is also second reason. Because of the lazy subscription, property may not store it's current value all the time although semantically have one. For example this property `Kefir.constant(1).map(times2)` will not store `2` in it's `._currentValue`, but when it gets first subscriber it immediately subscribe to `Kefir.constant(1)`, update it's `._currentValue` and provide result to the subscriber.

So implementation of `property.currentValue()` will be a bit ugly if we add it. And since it pretty easy to get current value with current API as you mentioned, I'd better not add `.currentValue()`.

**Comment by mhelvens** [comment]
> Yes one reason is that users not supposed to want this, but have to admit I have no clear explanation why this is bad, only some intuition feeling. Maybe @raimohanska could tell more about this.

I'd love to understand this better. Note that Bacon.js does offer this functionality through [bacon.model](https://github.com/baconjs/bacon.model). I've been using that for a while. But I'm migrating, so...

> Because of the lazy subscription, property may not store it's current value all the time although semantically have one.

Yes, I understand the problem with 'inactive' properties not (yet) having an up to date value. The solution is to make it internally active for the amount of time it takes to fetch the current value. Basically the code I gave above.

> And since it pretty easy to get current value with current API as you mentioned, I'd better not add .currentValue().

I wouldn't call that little workaround easy; not for casual use. It's certainly not intuitive. How about providing a `Property` subclass, like bacon.model?

**Comment by pozadi** [comment]
I also afraid people might overuse that feature e.g., will do things like:

```js
stream.map(function() {
  return property.currentValue();
});
```

instead of:

```js
property.sampledBy(stream);
```

I guess there might be a lot of cases how it might be overused.

**Comment by mhelvens** [comment]
Yes, but do you want to design this library for the lowest common denominator of developer?

>    // this won't work correctly if property doesn't have subscriber somewhere,

Not if you implement `.currentValue()` correctly (e.g., my 4 line example above, or a lower-level version of it). Outward behavior should always be as if the observable is active.

**Comment by pozadi** [comment]
> Not if you implement .currentValue() correctly (e.g., my 4 line example above, or a lower-level version of it).

I meant property will ignore values from its source while in hibernation (most of the time as we do `.offValue` right after `.onValue`), so it won't keep it's value properly updated, and user will get random values from `stream.map(...)`.

**Comment by raimohanska** [comment]
I'm pretty sure the only way to implement currentValue "correctly" is to make Properties always active, which in turn will have them never unsubscriber from their sources. The 4-line example works correctly for some cases but not nearly all.

**Comment by raimohanska** [comment]
So from where I stand it looks like currentValue doesn't belong to Property in Bacon or Kefir. In Bacon.Model it's feasible because the Model is always active.

**Comment by pozadi** [comment]
Yep, I think not having `.currentValue()` method forces users to subscribe to the property in order to get current value from it, which in turn activates the property and makes everything work.

**Comment by raimohanska** [comment]
You nailed it @pozadi !

**Comment by mhelvens** [comment]
I'm trying to understand. Could you give me an example case where my 4 line snippet wouldn't work? Perhaps I'm making certain assumptions that I shouldn't.

**Comment by pozadi** [comment]
```js
var property = Kefir.sequentially(1000, [1, 2, 3]).toProperty();
var stream = Kefir.sequentially(1000, [0, 0, 0]).delay(500);

property.sampledBy(stream).log();
// [sampledBy] <value> 1
// [sampledBy] <value> 2
// [sampledBy] <value> 3
// [sampledBy] <end>
```

```js
var property = Kefir.sequentially(1000, [1, 2, 3]).toProperty();
var stream = Kefir.sequentially(1000, [0, 0, 0]).delay(500);

Kefir.Property.prototype.currentValue = function() {
  var result;
  var save = function(x) {
    result = x;
  };
  this.onValue(save);
  this.offValue(save);
  return result;
};

stream.map(function() {
  return property.currentValue();
}).log();
// [sequentially.delay.map] <value> undefined
// [sequentially.delay.map] <value> undefined
// [sequentially.delay.map] <value> undefined
// [sequentially.delay.map] <end>

// But will work same as .sampledBy with this line uncommented
// property.onValue(function() {});
```

**Comment by mhelvens** [comment]
That's because`.sequentially` currently doesn't behave properly without a subscription, as you've mentioned in #43.

Referring back to that thread, the assumption I've been making in this discussion is that *`Observable`s always act as though they are active, but are internally lazy whenever possible.* This seems like the right behavior to strive for. The specifications of `.sequentially` imply that it starts counting the moment the stream is created, regardless of subscriptions. But it doesn't.

You could implement this by forcing `Sequentially` streams to be active for their whole lifetime. (This may be necessary for many of the observables you listed [here](https://github.com/pozadi/kefir/issues/43#issuecomment-73811200), but certainly not all.)

**Comment by pozadi** [comment]
I see, but we're not doing anything from #43 yet :)

**Comment by polkovnikov-ph** [comment]
@rpominov So, was it ever fixed?
