### ISSUE TITLE
extra `emitter` methods to use with `.withHandler` and `.fromBinder`

### ISSUE THREAD

**Issue by mhelvens** [pozadi/kefir#51]
It would be quite useful, for example, in a `.withHandler` handler, to be able to pass an event directly, and / or to plug a stream into an emitter:

    stream.withHandler(function (emitter, event) {
        if (event.type === 'end') {
            emitter.plug(Kefir.later(1000, 1)); // a 'last minute concat'
        } else {
            emitter.send(event); // just pass the event
        }
    })

Without this, some tedious branching-code would need to be written.

**Comment by pozadi** [comment]
Yep, something like `.emitEvent` in [emitter object](https://pozadi.github.io/kefir/#emitter-object) makes sense. As well as in [emitter stream](https://pozadi.github.io/kefir/#emitter), at least for consistency. Will add it soon.

**Comment by mhelvens** [comment]
How about `.plug`? (It does seem like Event and Pool and Bus might all bleed together a bit.)

**Comment by pozadi** [comment]
Not sure about this, not very easy to add, and will probably make `.withHandler` a bit heavier.

You can use `.flatMap` for this. And, if you need to handle all kind of events, something like this:

```js
stream.withHandler(function(event, emitter) {
  emitter.emit(event); // emitting event object as value, so all events available in next step
}).flatMap(function(event) { ... })
```
