### ISSUE TITLE
API compatibility with Bacon

### ISSUE THREAD

**Issue by omarstreak** [pozadi/kefir#60]
Have you thought about adding a bunch of aliases and such so that kefir becomes a drop-in replacement for baconjs?

We're using Bacon heavily in our codebase right now and running into some performance issues. I'd love to try out kefir, but the API differences makes that a pain. I don't know for sure that kefir will resolve the perf issues, so having to do the work of migrating some code over in an exploratory way is a big barrier.

I think this is something that lodash did extremely well. They had a "pure" version, and then an underscore compatible version - that made the migration extremely smooth and they're benefiting greatly for it.

**Comment by pozadi** [comment]
There is too much differences between two libs, it would be very hard to maintain such compatible version. Also Kefir simply doesn't have some of Bacon features.

See also comparison table, which I just created: https://github.com/pozadi/kefir/blob/master/bacon-vs-kefir-api.md
