### ISSUE TITLE
Multiple instances of kefir working together

### ISSUE THREAD

**Issue by omarstreak** [pozadi/kefir#62]
Bacon has a limitation that multiple versions of Bacon don't work together, does kefir have this same limitation?

An example:
* a library uses kefir streams internally
* the library accepts streams (rx, bacon and kefir) and "munges" them together
* obviously the rx and bacon streams need to be converted to kefir, but do the kefir streams have to be converted to the library's internal version of kefir?

**Comment by pozadi** [comment]
I think it will work. There is no global state in Kefir, and `instanceof` checks, which is the reasons of this limitation in Bacon as far as I know. But I didn't check if it actually works, and I'd try not to relay on this, as we might have to use global state or `instanceof` in the future.
