### ISSUE TITLE
It is not possible to use .emit function as a parameter to some other high-order function.

### ISSUE THREAD

**Issue by artemkozlov** [pozadi/kefir#65]
Lets say we have some simple high-order function and Emitter. And we want to use them together like:

```javascript
function apply(f) {
  return function(x) {
    return f(x);
  }
}

var emitter = Kefir.emitter();
apply(emitter.emit)(1);
```
But it fails with exception:
```
Uncaught TypeError: Cannot read property '_send' of undefined kefir.js:2234(anonymous function) @ VM80:4(anonymous function) @ VM80:9InjectedScript._evaluateOn @ VM61:888InjectedScript._evaluateAndWrap @ VM61:821InjectedScript.evaluate @ VM61:687
```

The workaround is to bind this for emit, but this kind of annoying:
```
apply(emitter.emit.bind(emitter))(1);
```

**Comment by pozadi** [comment]
Most of methods in Kefir are not bound to their context to minimize memory footprint. So yes, you have to do `.bind` when passing it somewhere, but I don't see it as a workaround, it's just a normal thing you have to do in JavaScript when working with most of libraries.
