### ISSUE TITLE
Map to WebWorker

### ISSUE THREAD

**Issue by markmarijnissen** [pozadi/kefir#67]
Hi @pozadi 

I've [created a way](https://github.com/markmarijnissen/kefir-webworker) to map a stream to a WebWorker like this:

In your main file:
```javascript
Kefir.emitter()
     .mapWithWorker(new Worker('worker.js'))
```

In your worker.js:
```
Kefir
	.fromMessage()
	// do stuff
	.toMessage();
```

Might be an interesting thing to add to the core. (Or do you prefer to keep the core mean and lean?)

**Comment by pozadi** [comment]
Interesting stuff! But yes, I think a separate project is a good place for things like this.

**Comment by markmarijnissen** [comment]
Cool :) I'll leave it in my own repo then!
