### ISSUE TITLE
scan() behaves differently when first even is a 'current' value

### ISSUE THREAD

**Issue by jimmydivvy** [pozadi/kefir#70]
When using scan, I can pass a seed value as the second argument. In most cases, the seed appears to be emitted as the first event. However if the input stream contains a 'current' value, the seed is only used on the first stateful transition and never emitted.

As an example:

    function add(x,y){return x+y};
    var head = Kefir.sequentially(0, [1])
    var tail = Kefir.sequentially(0, [10,20])
    Kefir.concat( [head, tail] ).scan( add, 100 ).log();

This scan function outputs the seed '100', and then accumulates the rest of the values correctly.

    [concat.scan] <value:current> 100
    [concat.scan] <value> 101
    [concat.scan] <value> 111
    [concat.scan] <value> 131
    [concat.scan] <end>

However when the input already has a value marked as 'current'

     var head = Kefir.constant(1)
     ....

The seed value is used as the initial state, but is never emitted

[concat.scan] <value:current> 101
[concat.scan] <value> 111
[concat.scan] <value> 131
[concat.scan] <end>

I've been scouring the documentation trying to work out if this is intended behaviour or not - it seems incorrect, and my intuition would be that the seed should never be emitted directly.

(Using version 1.1.0 from NPM)

**Comment by pozadi** [comment]
Seed is never being _emitted_. What happens is that scan returns a Property, and if source have no current value seed becomes current value of the result property. Then, when you subscribe, you get a current value in your subscriber function, which may be seed or result of handling current value of the source.
