### ISSUE TITLE
combineTemplate

### ISSUE THREAD

**Issue by theadam** [pozadi/kefir#75]
Any thoughts on adding functionality similar to combineTemplate from Baconjs?

**Comment by pozadi** [comment]
We discussed it in [gitter](https://gitter.im/pozadi/kefir) Sorry for being lazy, but I'll just copy-paste from there:

> Also my most recent idea about Kefir API is that it should be as small as possible (see #71) There is a lot of benefits from it, and boilerplate code isn't a big problem. So `.combineTemplate` the only value of which is minimizing boilerplate code, isn't good candidate to be added to the API.
