### ISSUE TITLE
Update transduce to Official Transformer Protocol

### ISSUE THREAD

**Issue by kevinbeaty** [pozadi/kefir#78]
Change transducers implementation to support "Official Transformer Protocol" discussed in cognitect-labs/transducers-js#20 .  Both transducers.js and transducers-js have been updated to support it.

Summary of changes:
```javascript
// anywhere you use a transformer
// (including transducer implementations)
var xf = {
   init: function()
   step: function(acc, item)
   result: function(acc)
}
// becomes
var xf = {
   '@@transducer/init': function()
   '@@transducer/step': function(acc, item)
   '@@transducer/result': function(acc)
}
// reduced wrapper object changes from 
{
   value: acc,
   __transducers_reduced__: true
}
// to
{
   '@@transducer/value': acc,
   '@@transducer/reduced':true
}
```

**Comment by pozadi** [comment]
I've added support of new protocol and old one also still supported. Will release patch version with this changes a bit later. Also going to remove support of old protocol in `v2.0.0`.

Thanks!
