### ISSUE TITLE
Transducers analogue to Kefir.scan

### ISSUE THREAD

**Issue by monfera** [pozadi/kefir#80]
I've been playing with Kefir for a while and test-driving the excellent integration with transducers. The following, seemingly simple task trips me up. It appears that transducers can be used analogously to the FRP mapping and filtering constructs, however what would be the idiomatic transducers pattern analogue for the FRP scan? Scan is basically a reduce (fold).

In this example, I'm using Kefir with transducers-js and d3 to generate points for a basic scatter plot and render them. At two points in the code (counter and pointSet), where I currently used closures, the former non-transducer code used scan.  

http://codepen.io/monfera/pen/pvmvMe?editors=001

What's the nicest way to express the counter and pointSet functions with transducers, without the closure workaround? Preferably I wouldn't want to step out of transducers with t.reduce() or Kefir.scan just so that I can fold. I feel it must be really simple bt  3:30am might be too late for me. Do I need to write a new transducer, maybe patterned after t.partitionBy?

**Comment by pozadi** [comment]
Interesting idea, but I can't fully understand how it would work. Perhaps you could give some example of usage of this new method (imagine it already implemented)?

**Comment by monfera** [comment]
Using the imaginary transducer 't.scan' to avoid naming ambiguity of anything 'reduce' in transducers-land:
 
var counter = t.scan(function(prev, next) {
  return prev + 1;
}, 0);

**Comment by pozadi** [comment]
Oh, I was thinking of something different, which probably won't work. But what you suggesting looks doable. Here is a draft of such transducer:

```js
function scan(handler, seed) {
  var prevValue = seed;
  return function(xf) {
    return {
      "@@transducer/init": function() { 
        return xf["@@transducer/init"]();
      },
      "@@transducer/result": function(result) { 
        return xf["@@transducer/result"](result);
      },
      "@@transducer/step": function(result, input) {
        var newValue = handler(prevValue, input);
        prevValue = newValue;
        return xf["@@transducer/step"](result, newValue);
      }
    };
  };
}
```

Usage example:
```js
var transducer = t.comp(
  t.map(function(x) {...}),
  t.filter(function(x) {...}),
  scan(function(prev, next) {return prev + 1}, 0),
  t.take(2)
);
var newStream = stream.transduce(transducer);
```

**Comment by monfera** [comment]
Awesome, I updated the example, works fine! It would be neat to be able to add such transducer functions at the user level, as long as all elements on which it relies are part of the transducers protocol (making it possible for transducer library users to extend the vocabulary without a version change breaking the add-ons). I had an old PR for an indexed map transducer but it is a slow merge: https://github.com/cognitect-labs/transducers-js/pull/21

Here's the updated version with your scanning transducer:

http://codepen.io/monfera/pen/pvmvMe?editors=001

**Comment by pozadi** [comment]
Cool, never thought that `.scan` also can be implemented as a transducer. Not a 100% match with `obs.scan()` (won't create property etc.) but pretty similar.

**Comment by monfera** [comment]
The motivation is that FRP is nicest to work with and  I really like your focus on high performance. Developing with FRP is most transparent (compared to pub/sub or even Clojure CSP) but it seems that all function boundaries are async. This makes impossible certain code optimisations, e.g. inlining, type inference and keyhole optimisations, and of course sometimes you just want synchronous behavior or materialisation (irrespective of performance benefits). I also noticed that FRP pollutes the stack in that 9 out of 10 stack frames will be FRP library frames, or with RxJS more like 19 out of 20. 

So ideally we can have the entire application logic defined in functional terms, and maybe add annotations or extra args where we want to materialize something into something specific (array, ES6 generator, hash map, crossfilter.js object, WebSockets stream when our logic spans client-server boundaries etc.), or we "inject" async-ness into the code once the code is finalized, assisted with (hopefully) less noisy stack traces.

The chaining style as in your FRP library looks preferable to me over the broilerplate of t.comp (I think the transducers prototype object can be enhanced to allow such chaining), but ideally the code would look as close to a regular functional solution as possible. For example, sampledBy and most other FRP things dictate a pattern where I put input streams into arrays, only to then doing a destructuring-bind in the function itself (x = tuple[0], y = tuple[1] etc.). ES6 helps with the binding (http://mzl.la/1A9rvw3) but it's still more verbose than the regular functional equivalent, e.g.

```javascript
var transform = Kefir.combine([translate, scale, skew], [], function(tuple) {
  var translate = tuple[0];
  var scale = tuple[1];
  var skew = tuple[2];
  // calculate the transform matrix from translate, scale, skew
  // ...
})
```

or with ES6:

```javascript
let transform = Kefir.combine([translate, scale, skew], [], function(tuple) {
  let [translate, scale, skew] = tuple;
  // calculate the transform matrix from translate, scale, skew
  // ...
})
```

vs the plain functional version:

```javascript
function transform(translate, scale, skew) {
  // calculate the transform matrix from translate, scale, skew
  // ...
}
```

**Comment by monfera** [comment]
Ah sorry, just noticed I no longer need to go through a tuple, so there is less broilerplate:

```javascript
let transform = Kefir.combine([translate, scale, skew], [], function(translate, scale, skew) {
  // calculate the transform matrix from translate, scale, skew
  // ...
})
```

**Comment by pozadi** [comment]
> I think the transducers prototype object can be enhanced to allow such chaining

Take a look at https://github.com/kevinbeaty/underarm

**Comment by monfera** [comment]
Thank you Roman, looks very interesting. Apparently, besides support for chaining, it has its own async parts (though apparently not FRP) and its own transducers implementation but it doesn't seem to follow the object based implementation that is common between transducers.js and transducers-js which are supported by Kefir, though on an initial look, there's no dependence on the internals. Maybe the tradeoff is slower speed? (My natural preference would be functional.) In some post I don't find jlongster said he did benchmarking to conclude that objects were the fastest.  I'm toying with 60FPS visualisations which is one reason I switched from RxJS to Kefir (simplicity and lower levels of stack pollution are another).

**Comment by pozadi** [comment]
As far a I know `underarm` supports same protocol as  `transducers.js/-js`, so ti should work with `Kefir`. Something like this:
```
stream.transduce(_r().filter(isEven).map(inc).value())
```

Also yes, it can do sort of FRP stuff by simply applying transducer to a function, which returns another function, which when called causes call of original one, but first passes the value through transducers chain — also pretty interesting stuff. This can be done with any transducers implementation, btw.

**Comment by monfera** [comment]
Looks very interesting, thanks! This also reminded me of Ramda, which seems to cover generally larger ground, although Ramda seems to have very few async tools. I found only two functions, e.g. one for promises. However, maybe Ramda's transducers also play nice with Kefir, will check it out soon.

**Comment by monfera** [comment]
Had some success with Kefir + Ramda transducers, though I got a "not transducer protocol compliant error" even though the Ramda guys merged a commit 2 days ago that purports to bring Ramda transducers into compliance. They assumed I'm behind the commit and closed the ticket (https://github.com/ramda/ramda/issues/1012#issuecomment-90269028).

However the reason I'm back is that the scan function on the top of this page, more precisely,

```javascript
kefirStream.scan(function...)
```
isn't replaceable, as it is, with the transducers version
```javascript
kefirStream.transduce(scan(function...))
```
because of, I suspect, the presence of multiple observers in my code. If the suspicion is true, then the proper step function isn't a single notification of a subscriber, because there can be several. The proper step function would be the triggering of the notifications, leading to multiple downstream executions. But maybe I'm wrong about the root cause, or maybe there is a fundamental limitation with transducers, or the combination of transducers and FRP. Why?

With FRP, it is possible to create a unidirectional data pipeline network that starts with N inputs (e.g. mouse events, http events etc.) and ends with M output (e.g. functions for updating various parts of the DOM, canvas, server etc.). Common nodes will be characterized with a shared execution. E.g. if we calculate something in the middle (e.g. a current game score accumulator, via a scan), then that specific calculation is executed once per input set. The analogous transducers solution would probably execute the function multiple times, as that calculation node would be included in multiple (in this case, three) executions which query what to put into the DOM, into the canvas and on the server.

So maybe, if transducers are used inside FRP, it is necessary to constrain the data pipelining to one singular output node, e.g. an array which captures all output elements, which then one function takes via finalStream.onValue(fun).

**Comment by pozadi** [comment]
I didn't quite understand your issue. You've only described the possible reasons of it, but not the issue itself.

**Comment by monfera** [comment]
I just tried to reduce the issue now to a minimal case (http://codepen.io/monfera/pen/KwjoMo?editors=001) but it doesn't reproduce the problem, I need to do further tests to isolate the case.
