### ISSUE TITLE
Creating stream for reading file using fromNodeCallback

### ISSUE THREAD

**Issue by ospatil** [pozadi/kefir#83]
I'm trying to create a stream to read file contents using _fs.readFile_. In BaconJS, I can achieve this by - 
```javascript
var readStream = Bacon.fromNodeCallback(fs.readFile, 'somefile.txt');

readStream.onValue(function (data) {
    //do something with data
});
```
I have checked API and specs but I see _Kefir.fromNodeCallback_ only accepts single function as argument. Am I missing something obvious? How can I achieve this in Kefir?

**Comment by pozadi** [comment]
You can use `.bind` like this: `Kefir.fromNodeCallback(fs.readFile.bind(fs, 'somefile.txt'))`
