### ISSUE TITLE
Changelog lacks dates

### ISSUE THREAD

**Issue by Merri** [pozadi/kefir#85]
While not absolutely necessary it would be very nice to see how the project has progressed over time when viewing the changelog without having to pull the repo just to see when the changelog has been edited.

**Comment by pozadi** [comment]
Currently this info available at the releases page https://github.com/pozadi/kefir/releases

Want to do a PR?

**Comment by Merri** [comment]
Did. Hopefully did it correctly as GitHub's explanation on pull requests is too verbose which leads to TL;DR.
