### ISSUE TITLE
Correct stream creation way

### ISSUE THREAD

**Issue by philosophocat** [pozadi/kefir#94]
Hi! 
First of all, thank you for Kefir.js, you're doing great thing ;)
My question is: Kefir.emitter() does not exists anymore. How should i use Kefir.stream(), if i have complex ui logic and it's necessary to have a stream of objects and these objects are emitted from different methods of module? What is the right way?

**Comment by pozadi** [comment]
Hi, here is the discussion on removing it: https://github.com/pozadi/kefir/issues/88 
It should help to understand why it is removed and what are the alternatives.

**Comment by philosophocat** [comment]
Anyway, i don't realize what are the alternatives. 
Example commented only 22 days ago, but its stuff is not actual: **Kefir.fromBinder** does not exists now, but ok, as i see, the idea is just to create a stream. I'll take smth like **Kefir.fromPoll(interval, fn)** with huge interval. 
But stream does not have emit() method. What i missed?

**Comment by pozadi** [comment]
`.fromBinder` renamed to `.stream` see changelog https://github.com/pozadi/kefir/blob/master/changelog.md

**Comment by philosophocat** [comment]
What about stream.emit(x)?

**Comment by pozadi** [comment]
There is no such method. Correct way to create a general purpose stream is to use `Kefir.stream(callback)`, and then emit events using `emitter` passed to the `callback`:

```
Kefir.stream(function(emitter) {
  emitter.emit(1);
});
```

**Comment by philosophocat** [comment]
Ohh.. Seems to be we do not understand each other. All i need is to emit() something from different functions. My issue is about it, and i can't solve it this way. For example, i have a function, that calculate "selection area" and checks element's location. How can i emit(element) from 
arbitrary function?

**Comment by pozadi** [comment]
I see. But what you want to do considered as a bad practice (see #88 and  [Bus of Doom](http://baconjs.blogspot.fi/2014/12/bus-of-doom.html)).

You can use deprecated [`Kefir.emitter()`](https://github.com/pozadi/kefir/blob/master/deprecated-api-docs.md#kefiremitter), but most likely you don't need it. Instead you should do something like this: http://jsfiddle.net/mw18nbrr/3/ (you'll only need to replace the final step from `var position = moves.scan(...)` to `var selectionArea = moves.scan(/* different handler, and initial value */)`)
