### ISSUE TITLE
Concat doesn't seem to be working correctly

### ISSUE THREAD

**Issue by natelokers** [pozadi/kefir#99]
This is my first time working with the library, so I could be wrong, but I'm having issues with concat.
I created this code that deals 24 cards into 4 hands, and then I concat the hands but it doesn't log anything.

```javascript
var dealer = Kefir.sequentially(5,[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]);
var deal = dealer.take(20);
var dealIndex = deal.scan(function(curr,val) { return curr + 1; },-1);

function getHandStream(deal,dealIndex,handCount,playerCount,playerIndex)
{
    return deal.filterBy(dealIndex.map(function(v) { return v%playerCount === playerIndex; })).take(handCount).bufferWhile(function() { return true; });
}

var player1Hand = getHandStream(deal,dealIndex,5,4,0);
var player2Hand = getHandStream(deal,dealIndex,5,4,1);
var player3Hand = getHandStream(deal,dealIndex,5,4,2);
var player4Hand = getHandStream(deal,dealIndex,5,4,3);
var trick = Kefir.concat([player1Hand,
                          player2Hand,
                          player3Hand,
                          player4Hand]).take(4).bufferWhile(function() { return true; });
trick.log();
```

However, if I add

```javascript
player1Hand.onValue(function() { });
player2Hand.onValue(function() { });
player3Hand.onValue(function() { });
player4Hand.onValue(function() { });
```

it works as expected.

**Comment by pozadi** [comment]
Heh, such a setup you have. Took me a while to get it)

The `.concat` works fine. 

Basically the issue lays near `s1 = s.bufferWhile(() => true)`. The content of `s1` depends on moment when you subscribe to it. It starts buffering when you subscribe. If you subscribe after all events passed, you'll get nothing. (see also http://pozadi.github.io/kefir/#active-state)

Notice that all your `playerXHand` streams have `.bufferWhile(() => true)` at the end. Now lets see how `.concat` subscribes to it sources: it subscribes to the next source when previous one ends. So it subscribes to `player2Hand` when `player1Hand` ends, but it's too late — `player2Hand` already missed all events. 

And what you need is simply replace `.concat` with `.merge`, which is right choice for this task.

**Comment by natelokers** [comment]
so why does the adding of the onValue() to the hands (or putting a .log() on them) cause it to work differently?

**Comment by pozadi** [comment]
Because:

> The content of s1 depends on moment when you subscribe to it. It starts buffering when you subscribe.

If you subscribe earlier, you get different result. With `.onValue()` both you and `.concat()` subscribe to streams, but you earlier.
